"""Auth-test fixtures — extends parent conftest with auth-specific env + users.

Parent ``tests/conftest.py`` already seeds ``SECRET_KEY`` and the basic env
vars. We add: ``FIRST_ADMIN_*``, ``FRONTEND_BASE_URL``, ``SMTP_*``,
``RESEND_API_KEY=""`` so any test that imports an app module gets a fully-
validated ``Settings()`` instance.

Fixtures:
- ``verified_user`` — INSERT a User with is_active=True, is_verified=True
- ``unverified_user`` — same shape but is_verified=False
- ``admin_user`` — is_superuser=True, is_verified=True
- ``mailpit_messages`` — async context that talks to Mailpit's HTTP API
  (clear between tests via DELETE, get via GET). Skipped if Mailpit is
  unreachable (running outside docker-compose).
"""

from __future__ import annotations

import os
from collections.abc import AsyncGenerator
from typing import TYPE_CHECKING

import pytest
import pytest_asyncio

# Phase 2 env seed — extends parent conftest's _DEFAULT_TEST_ENV. Done at
# import time so app.* imports inside test files see all required vars.
_PHASE2_TEST_ENV: dict[str, str] = {
    "FIRST_ADMIN_EMAIL": "",
    "FIRST_ADMIN_PASSWORD": "",
    "FRONTEND_BASE_URL": "http://localhost:3000",
    "SMTP_HOST": "mailpit",
    "SMTP_PORT": "1025",
    "RESEND_API_KEY": "",
}
for _k, _v in _PHASE2_TEST_ENV.items():
    os.environ.setdefault(_k, _v)


if TYPE_CHECKING:
    import httpx
    from sqlalchemy.ext.asyncio import AsyncSession

    from app.auth.models import User


# A pwdlib-hashed version of "Verified-Pass-1!" — generated once and pinned
# so we don't re-hash on every fixture invocation. The hash is generated by
# pwdlib's recommended() (Argon2id default in fastapi-users 15).
#
# To regenerate (DO NOT change the password):
#   from pwdlib import PasswordHash
#   PasswordHash.recommended().hash("Verified-Pass-1!")
_TEST_PASSWORD_PLAINTEXT = "Verified-Pass-1!"


def _hash_test_password() -> str:
    """Hash the test password using pwdlib (same as fastapi-users)."""
    from pwdlib import PasswordHash

    return PasswordHash.recommended().hash(_TEST_PASSWORD_PLAINTEXT)


@pytest_asyncio.fixture(loop_scope="session")
async def verified_user(async_session: AsyncSession) -> AsyncGenerator[User, None]:
    """A verified, active player user (no superuser flag)."""
    from sqlalchemy import delete

    from app.auth.models import User

    user = User(
        email="verified@example.com",
        hashed_password=_hash_test_password(),
        is_active=True,
        is_superuser=False,
        is_verified=True,
        display_name="Verified User",
    )
    async_session.add(user)
    await async_session.flush()
    try:
        yield user
    finally:
        # Clean up so subsequent tests in the same session don't see this row.
        # Use savepoint-safe deletion (rollback would also work but only at
        # session teardown).
        await async_session.execute(delete(User).where(User.id == user.id))
        await async_session.flush()


@pytest_asyncio.fixture(loop_scope="session")
async def unverified_user(async_session: AsyncSession) -> AsyncGenerator[User, None]:
    """An active but UNverified player user — for is_verified-gate tests."""
    from sqlalchemy import delete

    from app.auth.models import User

    user = User(
        email="unverified@example.com",
        hashed_password=_hash_test_password(),
        is_active=True,
        is_superuser=False,
        is_verified=False,
        display_name="Unverified User",
    )
    async_session.add(user)
    await async_session.flush()
    try:
        yield user
    finally:
        await async_session.execute(delete(User).where(User.id == user.id))
        await async_session.flush()


@pytest_asyncio.fixture(loop_scope="session")
async def admin_user(async_session: AsyncSession) -> AsyncGenerator[User, None]:
    """A superuser, verified, active user — for AUTH-07 tests (Plan 02-03)."""
    from sqlalchemy import delete

    from app.auth.models import User

    user = User(
        email="admin@example.com",
        hashed_password=_hash_test_password(),
        is_active=True,
        is_superuser=True,
        is_verified=True,
        display_name="Admin User",
    )
    async_session.add(user)
    await async_session.flush()
    try:
        yield user
    finally:
        await async_session.execute(delete(User).where(User.id == user.id))
        await async_session.flush()


@pytest.fixture
def test_password() -> str:
    """Return the plaintext password matching all *_user fixture hashes."""
    return _TEST_PASSWORD_PLAINTEXT


@pytest_asyncio.fixture
async def mailpit_messages() -> AsyncGenerator[httpx.AsyncClient, None]:
    """Yield an httpx client bound to Mailpit's HTTP API.

    Clears existing messages on enter; skipped if Mailpit is unreachable
    (running outside docker-compose).
    """
    import httpx

    base = os.environ.get("MAILPIT_HTTP_URL", "http://mailpit:8025")
    async with httpx.AsyncClient(base_url=base, timeout=2.0) as client:
        try:
            # DELETE clears all messages
            await client.delete("/api/v1/messages")
        except (httpx.ConnectError, httpx.ReadTimeout):
            pytest.skip("Mailpit HTTP API not reachable (run inside docker-compose)")
        yield client
